### ISSUE TITLE
I don't if I have the problem understanding or it is not well documented

### ISSUE THREAD

**Issue by alymohamedhassan** [waaaaargh/notifyme#6]
I don't know how to launch that project. Is it compiled to exe or should I execute it manually using the "python" cmd from CMD CLI.

Thanks.

**Comment by alymohamedhassan** [comment]
I was looking for an application that sends a notification to all phones or devices on my network, also nearby, but first let me finish this part.

**Comment by Profpatsch** [comment]
It’s a set of python scripts, so you can execute them with `python3`.

This project has long been dead, though, I’d recommend https://github.com/muesli/beehive/, which probably does what you want and is very much alive.

**Comment by waaaaargh** [comment]
Essentially, this is a library that allows you to pass notifications from one program to another over a network; Maybe even encrypted via TLS, but hell, the last commit is from 4 years ago, so at this point, honestly, your guess is as good as mine.

It is not, however an app that allows you to send notifications to a phone.
